name: CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
        
    - name: build database
      run: docker-compose -f ${{github.workspace}}/docker-compose.yml up --build -d db 

    - name: build backend
      run: docker-compose -f ${{github.workspace}}/docker-compose.yml up --build -d backend
      
    - name: tests
      run: docker exec backend python manage.py test
        
    - name: Stop containers
      if: always()
      run: docker-compose -f ${{github.workspace}}/docker-compose.yml down

  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Deploying to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: "<PROJECT-NAME>"
        heroku_email: "<EMAIL-ADDRESS>"
        healthcheck: "https://<PROJECT-NAME>.herokuapp.com/healthcheck"
        rollbackonhealthcheckfailed: true
      


    
